// <auto-generated />
using GamesApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GamesApi.Migrations
{
    [DbContext(typeof(GamesContext))]
    [Migration("20191206193928_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GamesApi.Models.GamesModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("dateReleased")
                        .HasColumnType("text");

                    b.Property<string>("gameGenre")
                        .HasColumnType("text");

                    b.Property<string>("gameName")
                        .HasColumnType("text");

                    b.Property<string>("synopsis")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GamesList");
                });
#pragma warning restore 612, 618
        }
    }
}
